services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  
  api-web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    
    
    
    container_name: new-django-docker
    ports:
      - "8000:8000"
    depends_on:
      - db
    
    volumes:
    - .:/app/
volumes:
   postgres_data:
   static_volume: